import { useMemo, useState } from 'react';
import type { Note } from '../lib/types';
import { fmtDMY, todayStr } from '../lib/util';
import { escapeHtml, sanitizeHtml } from '../lib/sanitize';

// Export a plain note (title + rich body) to OneNote and other targets. Notes
// have no agenda/actions — this is intentionally simpler than the meeting
// SharePanel. All interpolated text is escaped; the rich body is sanitised.

const stripToPlain = (s: string) =>
  (s || '')
    .replace(/<\/(p|div|li|h[1-3]|blockquote)>/gi, '\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<li[^>]*>/gi, '• ')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/[ \t]+\n/g, '\n').replace(/\n{2,}/g, '\n').trim();

// Compact fragment for pasting into a OneNote page.
function oneNoteHtml(note: Note): string {
  const f = "font-family:Calibri,'Segoe UI',sans-serif;";
  const title = note.title?.trim() || 'Untitled note';
  const body = (note.body || '').trim();
  const bodyHtml = body && body !== '<p></p>'
    ? `<div style="${f}font-size:13px;line-height:1.6;color:#333;">${sanitizeHtml(body)}</div>`
    : '';
  return `<h1 style="${f}font-size:20px;font-weight:700;margin:0 0 8px;">${escapeHtml(title)}</h1>${bodyHtml}`;
}

// Standalone document for download.
function fullHtml(note: Note): string {
  const title = note.title?.trim() || 'Untitled note';
  const body = (note.body || '').trim();
  const bodyHtml = body && body !== '<p></p>' ? sanitizeHtml(body) : '';
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${escapeHtml(title)}</title></head>
<body style="font-family:Calibri,'Segoe UI',sans-serif;max-width:720px;margin:0 auto;padding:28px 24px;color:#1A1A1A;background:#fff;">
  <h1 style="font-size:26px;font-weight:700;margin:0 0 4px;">${escapeHtml(title)}</h1>
  <div style="font-size:13px;color:#666;padding-bottom:14px;border-bottom:2px solid #217346;margin-bottom:14px;">${fmtDMY(note.updated_at || todayStr())}</div>
  <div style="font-size:13px;line-height:1.7;color:#333;">${bodyHtml}</div>
  <div style="font-size:11px;color:#bbb;margin-top:28px;padding-top:12px;border-top:1px solid #eee;">Generated by Cadence &nbsp;·&nbsp; ${fmtDMY(todayStr())}</div>
</body></html>`;
}

function plainText(note: Note): string {
  const title = note.title?.trim() || 'Untitled note';
  const body = stripToPlain(note.body || '');
  return [title, '', body, '', '— Generated by Cadence'].join('\n');
}

const isIOS = typeof navigator !== 'undefined' && /iPad|iPhone|iPod/.test(navigator.userAgent);
const canNativeShare = typeof navigator !== 'undefined' && !!navigator.share;
const canHtmlClipboard = !isIOS && typeof ClipboardItem !== 'undefined';

export function NoteSharePanel({ note, onClose }: { note: Note; onClose: () => void }) {
  const [copied, setCopied] = useState(false);
  const html = useMemo(() => oneNoteHtml(note), [note]);
  const docHtml = useMemo(() => fullHtml(note), [note]);
  const text = useMemo(() => plainText(note), [note]);

  const copy = async () => {
    try {
      if (canHtmlClipboard) {
        await navigator.clipboard.write([new ClipboardItem({ 'text/html': new Blob([html], { type: 'text/html' }) })]);
      } else {
        await navigator.clipboard.writeText(text);
      }
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.cssText = 'position:fixed;opacity:0;top:0;left:0;';
      document.body.appendChild(ta);
      ta.focus(); ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  const share = async () => {
    try { await navigator.share({ title: note.title || 'Note', text }); } catch { /* cancelled */ }
  };

  const download = () => {
    const blob = new Blob([docHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    if (isIOS) {
      window.open(url, '_blank');
      setTimeout(() => URL.revokeObjectURL(url), 15000);
    } else {
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(note.title || 'note').replace(/[^a-z0-9]/gi, '_')}.html`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  const primaryLabel = copied ? '✅ Copied!' : (canNativeShare && isIOS) ? '📤 Share…' : '📋 Copy for OneNote';
  const primaryAction = (canNativeShare && isIOS) ? share : copy;

  return (
    <div className="share-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="share-modal">
        <div className="share-hdr">
          <button className="btn btn-ghost btn-sm" onClick={onClose}>← Back</button>
          <div className="share-title">
            <div className="onenote-badge">N</div>
            Export Note
          </div>
          <button className="btn btn-ghost btn-sm" onClick={onClose}>✕</button>
        </div>

        <div className="share-preview">
          {isIOS
            ? <pre className="share-plain-preview">{text}</pre>
            : <div className="share-doc" dangerouslySetInnerHTML={{ __html: docHtml }} />}
        </div>

        <div className="share-actions">
          <button className={`share-primary-btn${copied ? ' copied' : ''}`} onClick={primaryAction}>
            {primaryLabel}
          </button>
          {canNativeShare && !isIOS && (
            <button className="share-secondary-btn" onClick={share}>📤 Share via…</button>
          )}
          <div className="share-secondary-row">
            <button className="share-secondary-btn" onClick={download}>
              {isIOS ? '🔗 Open file' : '⬇ Download .html'}
            </button>
          </div>
          <div className="share-hint">
            Paste straight into OneNote — the heading and formatting are preserved.
          </div>
        </div>
      </div>
    </div>
  );
}
