import React, { useMemo, useState } from 'react';
import { useCadence } from '../lib/store';
import type { Note, OutboxEmail, Person } from '../lib/types';
import type { MeetingData } from './MeetingNoteModal';

type Tab = 'full' | 'actions' | 'agenda' | 'onenote';

// ── Plain text generator (for native share + fallback clipboard) ──────────────
function generatePlainText(data: MeetingData, title: string, person: Person, createdAt: string, tab: Tab): string {
  const dateStr = new Date(createdAt).toLocaleDateString('en-GB', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  });
  const firstName = person.name.split(' ')[0];
  const lines: string[] = [title, dateStr, ''];

  if (tab !== 'actions') {
    const covered = data.agenda.filter((a) => a.status === 'covered');
    const toDiscuss = data.agenda.filter((a) => a.status === 'discuss');
    const deferred = data.agenda.filter((a) => a.status === 'deferred');
    if (covered.length || toDiscuss.length || deferred.length) {
      lines.push('AGENDA', '');
      covered.forEach((a) => { lines.push(`✅ ${a.title}`); if (a.notes) lines.push(`   ${a.notes}`); });
      toDiscuss.forEach((a) => { lines.push(`💬 ${a.title}`); if (a.notes) lines.push(`   ${a.notes}`); });
      deferred.forEach((a) => lines.push(`⏭ ${a.title} — deferred`));
      lines.push('');
    }
  }

  if (tab !== 'agenda' && data.actions.length) {
    lines.push('ACTION ITEMS', '');
    data.actions.forEach((a) => {
      const owner = a.owner === 'me' ? 'Rodney' : firstName;
      const due = a.due ? ` — Due ${new Date(a.due).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}` : '';
      lines.push(`${a.done ? '✓' : '☐'} ${a.title}`);
      lines.push(`   ${owner}${due}`);
    });
    lines.push('');
  }

  if (tab === 'full') {
    const body = (data.notes || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
    if (body) { lines.push('NOTES', '', body, ''); }
  }

  lines.push(`— Generated by Cadence`);
  return lines.join('\n');
}

// ── Rich HTML generator (for desktop clipboard + download) ────────────────────
function generateHtml(data: MeetingData, title: string, person: Person, createdAt: string, tab: Tab): string {
  const dateStr = new Date(createdAt).toLocaleDateString('en-GB', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  });
  const generatedOn = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const firstName = person.name.split(' ')[0];

  const sectionHead = (label: string) =>
    `<h2 style="font-family:Calibri,Segoe UI,sans-serif;font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#217346;border-bottom:2px solid #217346;padding-bottom:5px;margin:22px 0 12px;">${label}</h2>`;

  const agendaSection = (() => {
    if (tab === 'actions') return '';
    const covered = data.agenda.filter((a) => a.status === 'covered');
    const toDiscuss = data.agenda.filter((a) => a.status === 'discuss');
    const deferred = data.agenda.filter((a) => a.status === 'deferred');
    if (!covered.length && !toDiscuss.length && !deferred.length) return '';
    const itemHtml = (icon: string, a: { title: string; notes: string }) =>
      `<div style="display:flex;gap:10px;margin-bottom:9px;align-items:flex-start;">
        <span style="font-size:14px;">${icon}</span>
        <div>
          <div style="font-family:Calibri,Segoe UI,sans-serif;font-size:14px;font-weight:600;">${a.title}</div>
          ${a.notes ? `<div style="font-family:Calibri,Segoe UI,sans-serif;font-size:12px;color:#666;margin-top:2px;font-style:italic;">${a.notes}</div>` : ''}
        </div>
      </div>`;
    const deferredBlock = deferred.length
      ? `<div style="background:#FFF8EE;border-radius:6px;padding:9px 12px;margin-top:8px;border-left:3px solid #E07D00;">
          <div style="font-family:Calibri,Segoe UI,sans-serif;font-size:11px;font-weight:700;color:#E07D00;text-transform:uppercase;margin-bottom:5px;">Deferred to next meeting</div>
          ${deferred.map((a) => `<div style="font-family:Calibri,Segoe UI,sans-serif;font-size:13px;color:#E07D00;">⏭ ${a.title}</div>`).join('')}
        </div>` : '';
    return sectionHead('Agenda') + covered.map((a) => itemHtml('✅', a)).join('') + toDiscuss.map((a) => itemHtml('💬', a)).join('') + deferredBlock;
  })();

  const actionsSection = (() => {
    if (tab === 'agenda' || !data.actions.length) return '';
    const rows = data.actions.map((a) => {
      const isMe = a.owner === 'me';
      const ownerName = isMe ? 'Rodney' : firstName;
      const ownerColor = isMe ? '#6B3FA0' : '#1A7F37';
      const ownerBg = isMe ? '#F3EEFA' : '#EDFAF1';
      const borderColor = isMe ? '#1B5E9E' : '#217346';
      const dueStr = a.due ? new Date(a.due).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : '';
      return `<div style="display:flex;gap:10px;padding:9px 12px;border-radius:7px;background:#F8F8F6;border-left:3px solid ${borderColor};margin-bottom:8px;align-items:flex-start;">
        <span style="background:${ownerBg};color:${ownerColor};font-family:Calibri,Segoe UI,sans-serif;font-size:11px;font-weight:700;padding:2px 8px;border-radius:8px;white-space:nowrap;flex-shrink:0;margin-top:2px;">${ownerName}</span>
        <div>
          <div style="font-family:Calibri,Segoe UI,sans-serif;font-size:14px;font-weight:600;${a.done ? 'text-decoration:line-through;opacity:0.6;' : ''}">${a.title}</div>
          ${dueStr ? `<div style="font-family:Calibri,Segoe UI,sans-serif;font-size:11px;color:#666;margin-top:2px;">Due ${dueStr}</div>` : ''}
        </div>
      </div>`;
    });
    return sectionHead('Action Items') + rows.join('');
  })();

  const notesSection = (() => {
    if (tab !== 'full') return '';
    const body = (data.notes || '').trim();
    if (!body || body === '<p></p>') return '';
    return sectionHead('Notes') + `<div style="font-family:Calibri,Segoe UI,sans-serif;font-size:13px;line-height:1.7;color:#333;">${body}</div>`;
  })();

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${title}</title></head>
<body style="font-family:Calibri,'Segoe UI',sans-serif;max-width:720px;margin:0 auto;padding:28px 24px;color:#1A1A1A;background:#fff;">
  <h1 style="font-size:26px;font-weight:700;margin:0 0 4px;">${title}</h1>
  <div style="font-size:13px;color:#666;padding-bottom:14px;border-bottom:2px solid #217346;margin-bottom:2px;">${dateStr} &nbsp;·&nbsp; ${person.name}</div>
  ${agendaSection}${actionsSection}${notesSection}
  <div style="font-size:11px;color:#bbb;margin-top:28px;padding-top:12px;border-top:1px solid #eee;">Generated by Cadence &nbsp;·&nbsp; ${generatedOn}</div>
</body></html>`;
}

// ── OneNote table-cell generator (compact fragment, not a full document) ───────
function generateOneNoteHtml(data: MeetingData, person: Person, createdAt: string): string {
  const dateStr = new Date(createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const firstName = person.name.split(' ')[0];
  const f = 'font-family:Calibri,Segoe UI,sans-serif;';
  const parts: string[] = [];

  parts.push(`<p style="${f}font-size:13px;margin:0 0 6px;"><b>${dateStr}</b></p>`);

  const covered = data.agenda.filter((a) => a.status === 'covered');
  const discuss = data.agenda.filter((a) => a.status === 'discuss');
  const deferred = data.agenda.filter((a) => a.status === 'deferred');

  if (covered.length || discuss.length || deferred.length) {
    parts.push(`<ul style="${f}font-size:13px;margin:0 0 8px;padding-left:18px;">`);
    covered.forEach((a) => {
      const sub = a.notes ? `<ul style="padding-left:14px;margin:2px 0;"><li style="color:#555;font-style:italic;">${a.notes}</li></ul>` : '';
      parts.push(`<li>✅ <b>${a.title}</b>${sub}</li>`);
    });
    discuss.forEach((a) => parts.push(`<li>💬 <b>${a.title}</b> — not reached</li>`));
    deferred.forEach((a) => parts.push(`<li>⏭ <b>${a.title}</b> — deferred</li>`));
    parts.push('</ul>');
  }

  if (data.actions.length) {
    parts.push(`<p style="${f}font-size:13px;font-weight:700;margin:4px 0;"><b>Actions</b></p>`);
    parts.push(`<ul style="${f}font-size:13px;margin:0;padding-left:18px;">`);
    data.actions.forEach((a) => {
      const owner = a.owner === 'me' ? 'Rodney' : firstName;
      const due = a.due ? ` (Due ${new Date(a.due).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })})` : '';
      parts.push(`<li>${a.done ? '✓' : '☐'} <b>${owner}</b> — ${a.title}${due}</li>`);
    });
    parts.push('</ul>');
  }

  return parts.join('\n');
}

function generateOneNotePlain(data: MeetingData, person: Person, createdAt: string): string {
  const dateStr = new Date(createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const firstName = person.name.split(' ')[0];
  const lines: string[] = [dateStr, ''];

  data.agenda.filter((a) => a.status === 'covered').forEach((a) => {
    lines.push(`✅ ${a.title}`);
    if (a.notes) lines.push(`   ${a.notes}`);
  });
  data.agenda.filter((a) => a.status === 'discuss').forEach((a) => lines.push(`💬 ${a.title} — not reached`));
  data.agenda.filter((a) => a.status === 'deferred').forEach((a) => lines.push(`⏭ ${a.title} — deferred`));

  if (data.actions.length) {
    lines.push('', 'Actions');
    data.actions.forEach((a) => {
      const owner = a.owner === 'me' ? 'Rodney' : firstName;
      const due = a.due ? ` (Due ${new Date(a.due).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })})` : '';
      lines.push(`${a.done ? '✓' : '☐'} ${owner} — ${a.title}${due}`);
    });
  }

  return lines.join('\n');
}

// ── Capability detection ──────────────────────────────────────────────────────
const canNativeShare = typeof navigator !== 'undefined' && !!navigator.share;
// iOS Safari supports ClipboardItem but NOT text/html — only text/plain and image/png
const isIOS = typeof navigator !== 'undefined' && /iPad|iPhone|iPod/.test(navigator.userAgent);
const canHtmlClipboard = !isIOS && typeof ClipboardItem !== 'undefined';

// ── SharePanel ────────────────────────────────────────────────────────────────
interface Props {
  note: Note;
  person: Person;
  meetingData: MeetingData;
  onClose: () => void;
}

export function SharePanel({ note, person, meetingData, onClose }: Props) {
  const { insert } = useCadence();
  const [tab, setTab] = useState<Tab>('onenote');
  const [copied, setCopied] = useState(false);
  const [emailDone, setEmailDone] = useState(false);

  const html = useMemo(
    () => generateHtml(meetingData, note.title, person, note.created_at, tab),
    [meetingData, note.title, person.name, note.created_at, tab],
  );
  const plainText = useMemo(
    () => generatePlainText(meetingData, note.title, person, note.created_at, tab),
    [meetingData, note.title, person.name, note.created_at, tab],
  );
  const oneNoteHtml = useMemo(
    () => generateOneNoteHtml(meetingData, person, note.created_at),
    [meetingData, person.name, note.created_at],
  );
  const oneNotePlain = useMemo(
    () => generateOneNotePlain(meetingData, person, note.created_at),
    [meetingData, person.name, note.created_at],
  );

  const isOneNote = tab === 'onenote';

  // ── Copy / Share ─────────────────────────────────────────────────────────────
  const copyToClipboard = async () => {
    const htmlContent = isOneNote ? oneNoteHtml : html;
    const textContent = isOneNote ? oneNotePlain : plainText;
    try {
      if (canHtmlClipboard) {
        const blob = new Blob([htmlContent], { type: 'text/html' });
        await navigator.clipboard.write([new ClipboardItem({ 'text/html': blob })]);
      } else {
        await navigator.clipboard.writeText(textContent);
      }
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = textContent;
      ta.style.cssText = 'position:fixed;opacity:0;top:0;left:0;';
      document.body.appendChild(ta);
      ta.focus(); ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  // iOS native share sheet — best UX on iPhone/iPad
  const nativeShare = async () => {
    const textContent = isOneNote ? oneNotePlain : plainText;
    try {
      await navigator.share({ title: note.title, text: textContent });
    } catch {
      // User cancelled — no-op
    }
  };

  // ── Download ──────────────────────────────────────────────────────────────────
  const downloadHtml = () => {
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    if (isIOS) {
      window.open(url, '_blank');
      setTimeout(() => URL.revokeObjectURL(url), 15000);
    } else {
      const a = document.createElement('a');
      a.href = url; a.download = `${note.title.replace(/[^a-z0-9]/gi, '_')}.html`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  // ── Email to Outbox ───────────────────────────────────────────────────────────
  const sendEmail = async () => {
    await insert('outbox', {
      to: person.email || '',
      cc: '',
      subject: note.title,
      body: html,
      status: 'draft',
      related_project_id: null,
      related_work_item_id: null,
      created_by: 'you',
    } as Partial<OutboxEmail>);
    setEmailDone(true);
  };

  const primaryLabel = copied
    ? '✅ Copied!'
    : canNativeShare && isIOS
      ? '📤 Share…'
      : isOneNote
        ? '📋 Copy for OneNote'
        : canHtmlClipboard
          ? '📋 Copy for OneNote'
          : '📋 Copy text';

  const primaryAction = canNativeShare && isIOS ? nativeShare : copyToClipboard;

  const primaryHint = isOneNote
    ? 'Paste directly into your OneNote 1:1 table — date, topics covered, and actions'
    : isIOS
      ? 'Opens iOS share sheet — paste into OneNote, Notes, Mail and more'
      : 'Paste into OneNote — formatting, colours and action owners are preserved';

  const TABS: { key: Tab; label: string }[] = [
    { key: 'onenote', label: '📋 OneNote' },
    { key: 'full', label: 'Full' },
    { key: 'actions', label: 'Actions' },
    { key: 'agenda', label: 'Agenda' },
  ];

  return (
    <div className="share-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="share-modal">

        <div className="share-hdr">
          <button className="btn btn-ghost btn-sm" onClick={onClose}>← Back</button>
          <div className="share-title">
            <div className="onenote-badge">N</div>
            Share Summary
          </div>
          <button className="btn btn-ghost btn-sm" onClick={onClose}>✕</button>
        </div>

        <div className="share-tabs">
          {TABS.map(({ key, label }) => (
            <button key={key} className={`share-tab${tab === key ? ' active' : ''}`} onClick={() => setTab(key)}>
              {label}
            </button>
          ))}
        </div>

        <div className="share-preview">
          {isOneNote ? (
            <pre className="share-plain-preview">{oneNotePlain}</pre>
          ) : isIOS ? (
            <pre className="share-plain-preview">{plainText}</pre>
          ) : (
            <div className="share-doc" dangerouslySetInnerHTML={{ __html: html }} />
          )}
        </div>

        <div className="share-actions">
          <button className={`share-primary-btn${copied ? ' copied' : ''}`} onClick={primaryAction}>
            {primaryLabel}
          </button>

          {canNativeShare && !isIOS && (
            <button className="share-secondary-btn" onClick={nativeShare}>📤 Share via…</button>
          )}

          <div className="share-secondary-row">
            {person.email
              ? <button className="share-secondary-btn" onClick={sendEmail} disabled={emailDone}>
                  {emailDone ? '✓ In Outbox' : `✉ Email to ${person.name.split(' ')[0]}`}
                </button>
              : <span className="share-hint-sm">Add {person.name.split(' ')[0]}'s email in People to send</span>}
            <button className="share-secondary-btn" onClick={downloadHtml}>
              {isIOS ? '🔗 Open file' : '⬇ Download .html'}
            </button>
          </div>

          <div className="share-hint">{primaryHint}</div>
        </div>

      </div>
    </div>
  );
}

